### ISSUE TITLE
Add typing support

### ISSUE THREAD

**Issue by simmel** [Kreusada/python-dcl#4]
Hey Kreusada!

First, thank you for this library! It solved an issue I had to solve perfectly!

I see that you have typed some of the arguments to your methods but no return type and probably some other type related issues.

When I'm running mypy on my code I get:
```
error: Skipping analyzing "dcl": module is installed, but missing library stubs or py.typed marker  [import]
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

Sadly I'm under time constraints right now; otherwise I'd gladly contribute it!

This might be a good first issue for someone else?

**Comment by Kreusada** [comment]
Hi @simmel, sorry for the long wait on the response for this. I am working on a much improved implementation of the module which you can find in this PR (#5). The module is now fully typed, including a stub file ([``__init__.pyi``](https://github.com/Kreusada/python-dcl/pull/5/files#diff-e280583ea656961f9a79646c96e85eb52fc0b48bb18aaa37c66e808a7447fbe5)) to support static type checkers with the `@enum.global_enum` implementation. Any further comments or suggestions can be submitted to the attached pull request.
